### ISSUE TITLE
Mopidy 2.0 seems to break Mopidy-Pandora

### ISSUE THREAD

**Issue by jvonhoff** [rectalogic/mopidy-pandora#46]
After pip upgrading all of my mopidy extensions, I'm getting this message when I start mopidy:

`
ERROR    Setup of extension from entry point pandora failed, ignoring extension.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/ext.py", line 218, in load_extensions
    config_schema = extension.get_config_schema()
  File "/usr/lib/python2.7/site-packages/mopidy_pandora/__init__.py", line 21, in get_config_schema
    from pandora import BaseAPIClient
  File "/usr/lib/python2.7/site-packages/pandora/__init__.py", line 13, in <module>
    from .transport import APITransport, Encryptor, DEFAULT_API_HOST
  File "/usr/lib/python2.7/site-packages/pandora/transport.py", line 18, in <module>
    from Crypto.Cipher import Blowfish
  File "/usr/lib/python2.7/site-packages/Crypto/Cipher/Blowfish.py", line 55, in <module>
    from Crypto.Cipher import _create_cipher
ImportError: cannot import name _create_cipher
`

IIRC, the mopidy-gmusic extension upgraded some crypto libraries, so that may be the culprit.

**Comment by jcass77** [comment]
Those exceptions are actually occurring in the [pydora](https://github.com/mcrute/pydora) package which Mopidy-Pandora uses for communicating with the Pandora server.

Perhaps log the issue in that repository, and quote the version of ``pycrypto`` that you have installed (for reference: it still works with v2.6.1).

**Comment by jcass77** [comment]
...quick search on the web seems to indicate that there is a competing Blowfish implementation installed on your machine: [pycryptodome Blowfish.py](https://github.com/Legrandin/pycryptodome/blob/master/lib/Crypto/Cipher/Blowfish.py).

If that's the case, perhaps try uninstalling that and reverting to [pycrypto Blowfish.py](https://github.com/dlitz/pycrypto/blob/master/lib/Crypto/Cipher/Blowfish.py) (using ``pip``?).

It might just be a Python module collision that is causing the problem.

**Comment by jvonhoff** [comment]
Yes, I think you're right.  I'm not sure what's using pycryptodome, but I've uninstalled both pycryptodome and pycrypto, then reinstalled pycrypto (all using pip), and the errors have subsided.  Thanks a ton... I'll close this issue now.
